In [1]:
import numpy as np

In [2]:
np.array([1]).dtype

dtype('int32')

In [3]:
np.array([2.0]).dtype

dtype('float64')

In [8]:
numero = np.array([2.0], dtype=np.int32)

In [9]:
print(numero.dtype)

int32


In [10]:
print(numero)

[2]


# Operacoes

In [11]:
np.array([2]) + np.array([8])

array([10])

In [12]:
np.array([2]) - np.array([8])

array([-6])

In [13]:
np.array([2]) * np.array([8])

array([16])

In [14]:
np.array([2]) / np.array([8])

array([0.25])

In [15]:
np.array([2]) ** np.array([8])

array([256])

In [16]:
np.array([10]) % np.array([3])

array([1])

In [17]:
np.mod(np.array([10]), np.array([3]))

array([1])

In [18]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [20]:
a + 2

array([[3, 4],
       [5, 6]])

In [21]:
a * 10

array([[10, 20],
       [30, 40]])

In [22]:
np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [23]:
a @ b

array([[19, 22],
       [43, 50]])

In [24]:
a * b

array([[ 5, 12],
       [21, 32]])

In [25]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

In [26]:
a.T

array([[1, 3],
       [2, 4]])

In [27]:
arr = np.array([1,2,3,4,5])

In [28]:
np.sum(arr)

15

In [29]:
np.mean(arr)

3.0

In [30]:
np.median(arr)

3.0

In [31]:
np.std(arr)

1.4142135623730951

# Exercícios

In [32]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [33]:
arr_5 = arr*5
arr_5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [34]:
np.array([2.4], dtype=np.int32)

array([2])

In [36]:
np.mean(arr_5)

27.5

In [37]:
np.median(arr_5)

27.5

In [38]:
np.std(arr_5)

14.361406616345072

In [39]:
mean_normal = arr_5 - np.mean(arr_5)
mean_normal

array([-22.5, -17.5, -12.5,  -7.5,  -2.5,   2.5,   7.5,  12.5,  17.5,
        22.5])